
insert into USER (id, login, password, creation_time, status, mail, first_name, last_name) VALUES (1, 'Mike', '$2a$04$3HKHeP3YDbVeamlsEN5TgOflJstb4EJ0dLbvYvDXDfDunMSVdveSe', '2018-01-01 10:00:00+01', 'ACTIVATED', 'mike@mailinator.com', 'Michael', 'Jackson');
/*user password -> qwerty*/
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (1, 1, 'Pierwsza notatka', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (9, 2, 'Pierwsza notatka', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (10, 3, 'Pierwsza notatka', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (11, 4, 'Pierwsza notatka', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (12, 5, 'Pierwsza notatka', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (2, 6, 'Druga notatka', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (3, 7, 'Trzecia notatka', 'ĄĘLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (4, 8, 'Trzecia notatka', 'ĄĘLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (5, 9, 'Trzecia notatka', 'ĄĘLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (6, 10, 'Trzecia notatka', 'ĄĘLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (7, 11, 'Trzecia notatka', 'ĄĘLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (8, 12, 'Trzecia notatka', 'ĄĘLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. fasdfasfa asdfafdasf fasdfadfasd fasdfdsafdsa fsadfdasf safdfasdfadsfasd fasdfdsafadsf afsdfsadfasdf afsdfdsafdsa fsdafdsafads fsdafsadfdsa sdfhsdhs shdfhgdd sghfhdgdfg gfhgdhdfdhfg sdgffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', 1, '2018-01-01 10:00:00+01');
insert into NOTE (id, per_user_id, title, content, user_id, creation_time) VALUES (13, 13, 'Trzecia notatka', 'ĄĘLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. fasdfasfa asdfafdasf fasdfadfasd fasdfdsafdsa fsadfdasf safdfasdfadsfasd fasdfdsafadsf afsdfsadfasdf afsdfdsafdsa fsdafdsafads fsdafsadfdsa sdfhsdhs shdfhgdd sghfhdgdfg gfhgdhdfdhfg sdgffdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd', 1, '2018-01-01 10:00:00+01');